require('dotenv').config();
const mongoose = require('mongoose');
const ClothingItem = require('./models/clothingItem');

mongoose.connect(process.env.DB, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
  useCreateIndex: true,
});

async function seedBase() {
  const clothes = [
    new ClothingItem({
      name: 'backpack',
      type: 'accessory-bag',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'sport-hiking', 'leasure-walking'],
      imgUrl: './img/backpack.png',
    }),
    new ClothingItem({
      name: 'bag',
      type: 'accessory-bag',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout',],
      imgUrl: './img/bag1.png',
    }),
    new ClothingItem({
      name: 'bag',
      type: 'accessory-bag',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/bag2.png',
    }),
    new ClothingItem({
      name: 'bag',
      type: 'accessory-bag',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout',],
      imgUrl: './img/bag3.png',
    }),
    new ClothingItem({
      name: 'bag',
      type: 'accessory-bag',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/bag4.png',
    }),
    new ClothingItem({
      name: 'belt',
      type: 'accessory-belt',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/belt1.png',
    }),
    new ClothingItem({
      name: 'belt',
      type: 'accessory-belt',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/belt2.png',
    }),
    new ClothingItem({
      name: 'hat',
      type: 'hat',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot', 'warm'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/hat1.png',
    }),
    new ClothingItem({
      name: 'baseball cap',
      type: 'hat',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot', 'warm', 'cold'],
      activityFor: ['work-informal', 'leasure-walking', 'sport-jogging', 'sport-hiking'],
      imgUrl: './img/hatBaseball.png',
    }),
    new ClothingItem({
      name: 'bobble hat',
      type: 'hat',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      imgUrl: './img/hatBonbon.png',
    }),
    new ClothingItem({
      name: 'warm hat',
      type: 'hat',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      imgUrl: './img/hatWarm.png',
    }),
    new ClothingItem({
      name: 'headphones',
      type: 'hat',
      weatherFor: ['clear', 'clouds'],
      temperatureFor: ['cold', 'freeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      imgUrl: './img/headPhones.png',
    }),
    new ClothingItem({
      name: 'sunglasses',
      type: 'accessory-glasses',
      weatherFor: ['clear'],
      temperatureFor: ['hot', 'warm'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-hiking'],
      imgUrl: './img/glassesSun1.png',
    }),
    new ClothingItem({
      name: 'sunglasses',
      type: 'accessory-glasses',
      weatherFor: ['clear'],
      temperatureFor: ['hot', 'warm'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-hiking'],
      imgUrl: './img/glassesSun2.png',
    }),
    new ClothingItem({
      name: 'glasses',
      type: 'accessory-glasses',
      weatherFor: ['clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/glassesOffice.png',
    }),
    new ClothingItem({
      name: 'glasses',
      type: 'accessory-glasses',
      weatherFor: ['clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/glassesPointed.png',
    }),
    new ClothingItem({
      name: 'glasses',
      type: 'accessory-glasses',
      weatherFor: ['clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/glassesRound.png',
    }),
    new ClothingItem({
      name: 'umbrella',
      type: 'accessory-umbrella',
      weatherFor: ['rain'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      imgUrl: './img/umbrella.png',
    }),
    new ClothingItem({
      name: 'scarf',
      type: 'scarf',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      imgUrl: './img/scarf.png',
    }),
    new ClothingItem({
      name: 'gown',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home'],
      layer: 2,
      imgUrl: './img/gown.png',
    }),
    new ClothingItem({
      name: 'vest',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-jogging', 'sport-hiking'],
      layer: 1,
      imgUrl: './img/vest.png',
    }),
    new ClothingItem({
      name: 'white t-shirt',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home', 'work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-jogging', 'sport-hiking'],
      layer: 2,
      imgUrl: './img/tshirt1.png',
    }),
    new ClothingItem({
      name: 'striped t-shirt',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-jogging', 'sport-hiking'],
      layer: 2,
      imgUrl: './img/tshirt2.png',
    }),
    new ClothingItem({
      name: 'sleeveless shirt',
      type: 'top',
      weatherFor: ['clear', 'clouds'],
      temperatureFor: ['hot', 'warm'],
      activityFor: ['chilling-at-home', 'work-informal', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/shirtSleeveless.png',
    }),
    new ClothingItem({
      name: 'polo',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot', 'warm'],
      activityFor: ['chilling-at-home', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/polo.png',
    }),
    new ClothingItem({
      name: 'casual shirt',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot', 'warm'],
      activityFor: ['chilling-at-home', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/shirtRelaxed.png',
    }),
    new ClothingItem({
      name: 'striped shirt',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 3,
      imgUrl: './img/shirt1.png',
    }),
    new ClothingItem({
      name: 'gingham shirt',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 3,
      imgUrl: './img/shirt2.png',
    }),
    new ClothingItem({
      name: 'jumper',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home', 'work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 3,
      imgUrl: './img/jumper1.png',
    }),
    new ClothingItem({
      name: 'warm jumper',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['cold', 'freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home', 'work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      layer: 4,
      imgUrl: './img/jumper2.png',
    }),
    new ClothingItem({
      name: 'cardigan',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['cold', 'freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 4,
      imgUrl: './img/cardigan.png',
    }),
    new ClothingItem({
      name: 'suit jacket',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout'],
      layer: 5,
      imgUrl: './img/jacketSuit.png',
    }),
    new ClothingItem({
      name: 'light jacket',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['warm', 'cold', 'freeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 5,
      imgUrl: './img/jacketLight.png',
    }),
    new ClothingItem({
      name: 'biker jacket',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['warm', 'cold'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 5,
      imgUrl: './img/jacketBiker.png',
    }),
    new ClothingItem({
      name: 'raincoat',
      type: 'top',
      weatherFor: ['rain'],
      temperatureFor: ['warm', 'cold'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 5,
      imgUrl: './img/jacketRain.png',
    }),
    new ClothingItem({
      name: 'wind jacket',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['warm', 'cold'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-jogging', 'sport-hiking'],
      layer: 5,
      imgUrl: './img/jacketWind.png',
    }),
    new ClothingItem({
      name: 'warm hoodie',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      layer: 5,
      imgUrl: './img/hoodie1.png',
    }),
    new ClothingItem({
      name: 'hoodie',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      layer: 5,
      imgUrl: './img/hoodie2.png',
    }),
    new ClothingItem({
      name: 'warm jacket',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'work-office', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-jogging', 'sport-hiking'],
      layer: 6,
      imgUrl: './img/jacketWarm.png',
    }),
    new ClothingItem({
      name: 'coat',
      type: 'top',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'work-office', 'leasure-goingout', 'leasure-walking'],
      layer: 6,
      imgUrl: './img/coat.png',
    }),
    new ClothingItem({
      name: 'suit trousers',
      type: 'bottom',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout'],
      layer: 2,
      imgUrl: './img/trousersSuit.png',
    }),
    new ClothingItem({
      name: 'suit trousers',
      type: 'bottom',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout'],
      layer: 2,
      imgUrl: './img/trousersSuit.png',
    }),
    new ClothingItem({
      name: 'sport pants',
      type: 'bottom',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-jogging', 'sport-hiking'],
      layer: 2,
      imgUrl: './img/pantsSport.png',
    }),
    new ClothingItem({
      name: 'casual pants',
      type: 'bottom',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/pantsCasual.png',
    }),
    new ClothingItem({
      name: 'thermal pants',
      type: 'bottom',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'work-office', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking', 'sport-cycling'],
      layer: 1,
      imgUrl: './img/pantsThermo.png',
    }),
    new ClothingItem({
      name: 'shorts',
      type: 'bottom',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/shorts.png',
    }),
    new ClothingItem({
      name: 'shorts',
      type: 'bottom',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot', 'warm'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking', 'sport-jogging', 'sport-hiking'],
      layer: 2,
      imgUrl: './img/shortsLong.png',
    }),
    new ClothingItem({
      name: 'ugg',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'snow'],
      temperatureFor: ['cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/ugg.png',
    }),
    new ClothingItem({
      name: 'slippers',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['chilling-at-home'],
      layer: 2,
      imgUrl: './img/slippers.png',
    }),
    new ClothingItem({
      name: 'sneakers',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['sport-winter', 'sport-jogging', 'sport-hiking', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/shoes1.png',
    }),
    new ClothingItem({
      name: 'sneakers',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot', 'warm', 'cold'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/shoes2.png',
    }),
    new ClothingItem({
      name: 'office shoes',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['hot', 'warm', 'cold'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout'],
      layer: 2,
      imgUrl: './img/shoes3.png',
    }),
    new ClothingItem({
      name: 'office boots',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-office', 'leasure-goingout'],
      layer: 2,
      imgUrl: './img/boots.png',
    }),
    new ClothingItem({
      name: 'high boots',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['cold', 'freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 2,
      imgUrl: './img/bootsHigh.png',
    }),
    new ClothingItem({
      name: 'winter boots',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-goingout', 'leasure-walking', 'sport-winter', 'sport-hiking'],
      layer: 2,
      imgUrl: './img/bootsWinter.png',
    }),
    new ClothingItem({
      name: 'socks',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['warm', 'cold', 'freeze'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking', 'sport-cycling', 'sport-jogging', 'sport-winter', 'sport-hiking'],
      layer: 1,
      imgUrl: './img/socks.png',
    }),
    new ClothingItem({
      name: 'short socks',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain'],
      temperatureFor: ['hot', 'warm', 'cold'],
      activityFor: ['work-office', 'work-informal', 'leasure-goingout', 'leasure-walking'],
      layer: 1,
      imgUrl: './img/socksShort.png',
    }),
    new ClothingItem({
      name: 'socks',
      type: 'shoes',
      weatherFor: ['clear', 'clouds', 'rain', 'snow'],
      temperatureFor: ['freeze', 'extraFreeze'],
      activityFor: ['work-informal', 'leasure-walking', 'sport-winter', 'sport-hiking', 'chilling-at-home'],
      layer: 1,
      imgUrl: './img/socksWarm.png',
    }),
  ];

  // await mongoose.connection.dropDatabase();
  await ClothingItem.insertMany(clothes);
  await mongoose.disconnect();
}

seedBase();
