export const ADD_WEATHER_LOADER = 'ADD_WEATHER_LOADER';
export const REMOVE_WEATHER_LOADER = 'REMOVE_WEATHER_LOADER';
export const ADD_CLOTHES_LOADER = 'ADD_CLOTHES_LOADER';
export const REMOVE_CLOTHES_LOADER = 'REMOVE_CLOTHES_LOADER';
